"""create core entities: locations organisations developers applications

Revision ID: cbb0d6b57968
Revises: af12aaf7dddf
Create Date: 2026-09-12 11:03:03.190984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbb0d6b57968'
down_revision: Union[str, Sequence[str], None] = 'af12aaf7dddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('location_type', sa.String(length=50), nullable=False, comment='country, state, region, city, etc.'),
    sa.Column('country_code', sa.String(length=2), nullable=False, comment='ISO 3166-1 alpha-2 code'),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name=op.f('ck_locations_ck_location_latitude_range')),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name=op.f('ck_locations_ck_location_longitude_range')),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], name=op.f('fk_locations_parent_id_locations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations'))
    )
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)
    op.create_index(op.f('ix_locations_slug'), 'locations', ['slug'], unique=True)
    op.create_table('organisations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('organisation_type', sa.String(length=50), nullable=False, comment='startup, company, government, ngo, research, development, etc.'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('year_founded', sa.Integer(), nullable=True),
    sa.Column('headquarters_location_id', sa.UUID(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), server_default='unverified', nullable=False, comment='unverified, verified, rejected, etc.'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('year_founded IS NULL OR (year_founded >= 1900 AND year_founded <= EXTRACT(YEAR FROM NOW()))', name=op.f('ck_organisations_ck_organisation_year_founded_range')),
    sa.ForeignKeyConstraint(['headquarters_location_id'], ['locations.id'], name=op.f('fk_organisations_headquarters_location_id_locations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organisations'))
    )
    op.create_index(op.f('ix_organisations_name'), 'organisations', ['name'], unique=False)
    op.create_index(op.f('ix_organisations_slug'), 'organisations', ['slug'], unique=True)
    op.create_table('applications',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('launch_year', sa.Integer(), nullable=True),
    sa.Column('owning_organisation_id', sa.UUID(), nullable=True),
    sa.Column('access_type_id', sa.UUID(), nullable=True),
    sa.Column('availability_status_id', sa.UUID(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), server_default='unverified', nullable=False, comment='unverified, verified, rejected, etc.'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('launch_year IS NULL OR (launch_year >= 1900 AND launch_year <= EXTRACT(YEAR FROM NOW()))', name=op.f('ck_applications_ck_application_launch_year_range')),
    sa.ForeignKeyConstraint(['access_type_id'], ['access_types.id'], name=op.f('fk_applications_access_type_id_access_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['availability_status_id'], ['availability_statuses.id'], name=op.f('fk_applications_availability_status_id_availability_statuses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owning_organisation_id'], ['organisations.id'], name=op.f('fk_applications_owning_organisation_id_organisations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications'))
    )
    op.create_index(op.f('ix_applications_name'), 'applications', ['name'], unique=False)
    op.create_index(op.f('ix_applications_slug'), 'applications', ['slug'], unique=True)
    op.create_table('developers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('developer_type', sa.String(length=50), nullable=False, comment='individual, team, company, etc.'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), server_default='unverified', nullable=False, comment='unverified, verified, rejected, etc.'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_developers_organisation_id_organisations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_developers'))
    )
    op.create_index(op.f('ix_developers_name'), 'developers', ['name'], unique=False)
    op.create_index(op.f('ix_developers_slug'), 'developers', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_developers_slug'), table_name='developers')
    op.drop_index(op.f('ix_developers_name'), table_name='developers')
    op.drop_table('developers')
    op.drop_index(op.f('ix_applications_slug'), table_name='applications')
    op.drop_index(op.f('ix_applications_name'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_organisations_slug'), table_name='organisations')
    op.drop_index(op.f('ix_organisations_name'), table_name='organisations')
    op.drop_table('organisations')
    op.drop_index(op.f('ix_locations_slug'), table_name='locations')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
